language: php

services:
  - docker

php:
  - '7.2'

git:
  depth: 1

before_install:
  - curl -Ls https://raw.githubusercontent.com/unb-libraries/dockworker/3.x/scripts/travis/init.sh | bash
  - composer install

script:
  - set -e
  - vendor/bin/dockworker local:build-test
  - vendor/unb-libraries/dockworker/scripts/kubectl/init.sh
  - vendor/bin/dockworker image:deploy $TRAVIS_BRANCH
  - vendor/bin/dockworker deployment:logs:check $TRAVIS_BRANCH

notifications:
  slack:
    rooms:
      secure: dyyK292vCE0KzzZtFFm1VNt2ct3Mhltugjed2vmnwsxaTgKcQsWHnALlAr9EOpnogVSdd4/Xl23MMffiuNcA7ZiCcyZTnNYqRly4e0aJfRMHSHpj2flEktjOPHgKqOiKn6jK49GANJ+EJcWwzCWE8hXnVeOQLdvPdRXVSTm7VCT/8IanI4z/0fW2LM437zacuNr7oVZxKIEGlvmtEVphAKdOsL1hXlO9pZdONg/A9EJG0IJT4dnG1oznsS6jx+cdfMxeGlbMr7V0MhnwlZ9FfYPoH7NEfrpCHClEUYEPetREGaVuEG8R2QDNgbtipy3s+QmCdeJQEQigvRhnJmWneMPIEaV7KUMfkt92TYBmTNlAV4dVzuw+jm8OQe3gxCPUQ7uoPR4wF6TWRbyp2IUsNGQy5VhNZwapqWhmrQ/lQNrPcz5IeKPjawaPWwBTZs+9dgUicy0j+GhBkQTksFqTlhfZqu5k1fNg3/5KGOwNauz7SVJ51YQFGSxDsCcpKmVT49dk9rHFXgCzUe0+sjyAkvm8EXguaaT5mNvmENTO5H6TYmrCrWxazkZpxOHdewSyHcEmkFbMVE+iORHrDuOk/jyQJupqvPgU0RzuyZi07be9/Mc+nu9uvcODymQnOK7VCTZremZE68u38oUVDcVwGAHyoZ0nT58e7qvN1F44V6g=
    on_start: always
    on_success: always
