apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: solr
    tier: search
    appMajor: "8"
    uri: dev-drupal.solr.lib.unb.ca
  name: drupal-solr-lib-unb-ca
  namespace: dev
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: solr
        tier: search
        appMajor: "8"
        uri: dev-drupal.solr.lib.unb.ca
    spec:
      containers:
        -
          name: drupal-solr-lib-unb-ca
          readinessProbe:
            tcpSocket:
              port: 8983
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
          livenessProbe:
            tcpSocket:
              port: 8983
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 30
          env:
            -
              name: SOLR_HOME
              value: "/solr_home"
#            -
#              name: INIT_SOLR_HOME
#              value: "yes"
          image: "||DEPLOYMENTIMAGE||"
          imagePullPolicy: Always
          ports:
            -
              containerPort: 8983
              name: solr
          volumeMounts:
            -
              mountPath: /solr_home
              name: solr-persistent-storage
      priorityClassName: dev-high-priority-services
      restartPolicy: Always
      volumes:
        -
          name: solr-persistent-storage
          persistentVolumeClaim:
            claimName: drupal-solr-lib-unb-ca
